- name: Check that the somefile.conf exists
  stat:
    path: "{{ configdir }}/consul.d/consul-agent-ca.pem"
  register: stat_result

- name: Consul TLS client
  shell: "consul tls ca create && consul tls cert create -server -dc {{ datacenter }} && consul tls cert create -client -dc {{ datacenter }}"
  args:
    chdir: "{{ configdir }}/consul.d"
  when: not stat_result.stat.exists

- name: Install consul-template
  package:
    name: "consul-template"
    state: present