---

- name: restart consul
  systemd:
    name: consul
    state: restarted
- name: restart vault
  systemd:
    name: vault
    state: restarted
- name: restart nomad
  systemd:
    name: nomad
    state: restarted

- name: restart container
  systemd:
    name: "{{ container_engine | default('podman') }}"
    state: restarted

# Handler showing how to clean yum metadata cache
- name: yum-clean-metadata
  command: yum clean metadata
  args:
    warn: no
