---
- name: Ensure Consul is in a running state
  service:
    name: consul
    state: started
  register: consulServiceDetails
  until: consulServiceDetails.status.ActiveState == "active"
  retries: 15
  delay: 20

- name: Create policies
  include_tasks: write-policies.yml
  vars:
    acl_name: "{{ item.name }}"
    acl_desc: "{{ item.descr }}"
  with_items:
  - { name: "node", descr:  "Node Token" }
  - { name: "nomad", descr: "Nomad Service Token" }
  - { name: "vault", descr: "Vault Service Token" }
  - { name: "traefik", descr: "Traefik Catalog Service Token" }

