---
- name: Wait 30s for consul to start properly
  wait_for:
    timeout: 30
  delegate_to: localhost
  become: no

- name: Create policies
  include_tasks: write-policies.yml
  vars:
    acl_name: "{{ item.name }}"
    acl_desc: "{{ item.descr }}"
  with_items:
  - { name: "node", descr:  "Node Token" }
  - { name: "nomad", descr: "Nomad Service Token" }
  - { name: "vault", descr: "Vault Service Token" }
  - { name: "traefik", descr: "Traefik Catalog Service Token" }

- name: Setup consul again to refresh config file
  include_role:
    name: install-hashi
  vars:
    name: consul
    port_list: "{{ consul.port_list }}"

#- name: set agent token
#  shell: "consul acl set-agent-token -token='{{ consul_bootstrap_token }}' agent {{ consul_node_token }}"
