---
- name: Wait 30s for consul to start properly
  wait_for:
    timeout: 30
  delegate_to: localhost
  become: no

- name: Create policies
  include_tasks: write-policies.yml
  vars:
    acl_name: "{{ item }}"
  with_items:
  - node
  - nomad-service
  - vault-service

- name: Read or create keys
  include_role:
    name: read-or-get-key
  vars:
    key_name: "{{ item.name }}"
    key_folder: "{{ playbook_dir }}/.consul/policies"
    cmd: "{{ item.getter }}"
  with_items:
    - { name: consul_node_token, getter: "consul acl token create -description 'Node Token' -token='{{ consul_bootstrap_token }}' -policy-name node -format=json | jq -r '.SecretID'" }
    - { name: consul_vault_token, getter: "consul acl token create -description 'Vault Service Token' -token='{{ consul_bootstrap_token }}' -policy-name vault-service -format=json | jq -r '.SecretID'" }
    - { name: consul_nomad_token, getter: "consul acl token create -description 'Nomad Service Token' -token='{{ consul_bootstrap_token }}' -policy-name nomad-service -format=json | jq -r '.SecretID'" }

- name: Setup consul again to refresh config file
  include_role:
    name: install-hashi
  vars:
    name: consul
    port_list: "{{ consul.port_list }}"

#- name: set agent token
#  shell: "consul acl set-agent-token -token='{{ consul_bootstrap_token }}' agent {{ consul_node_token }}"
