# This should succeed regardless of seal state
- name: "Policy {{ acl_name }} exists?"
  # Attempt to help with long lines > 160 issues
  shell:
    cmd: consul acl policy list -token={{ consul_bootstrap_token }} -format=json | jq -r '.[] | select(.Name == "{{ acl_name }}") | .ID'
  register: check_result

- set_fact:
    acl_exists: "{{check_result.rc == 0 and check_result.stdout != '' }}"

- set_fact:
    tern: "{{ acl_exists | ternary('update', 'create') }}"
    acl: "{{lookup('file', acl_name +'.hcl') | trim | regex_replace('[\\r\\n]+','\n')}}"

- name: "Create ACL {{ acl_name }} policy"
  shell:
    cmd: "consul acl policy {{ acl_exists | ternary('update', 'create') }} -name {{ acl_name }} -token='{{ consul_bootstrap_token }}' -rules -"
    stdin: "{{acl}}"
  environment:
    CONSUL_HTTP_TOKEN: consul_bootstrap_token

- name: Read or create keys
  include_role:
    name: read-or-get-key
  vars:
    key_name: "consul_{{ acl_name }}_token"
    cmd: "consul acl token create -description '{{ acl_desc }}' -token='{{ consul_bootstrap_token }}' -policy-name {{ acl_name }} -format=json | jq -r '.SecretID'"

- name: Restart consul
  meta: noop
  notify:
  - consul config changed