# This should succeed regardless of seal state
- name: "Policy {{ acl_name }} exists?"
  # Attempt to help with long lines > 160 issues
  shell:
    cmd: consul acl policy list -token={{ consul_bootstrap_token }} -format=json | jq -r '.[] | select(.Name == "{{ acl_name }}") | .ID'
  retries: 5
  delay: 20
  until: check_result is not failed
  failed_when: "'Failed to retrieve the policy list' in check_result.stderr or check_result.rc != 0"
  environment:
    CONSUL_HTTP_SSL_VERIFY: "false"
  register: check_result

- set_fact:
    acl_exists: "{{check_result.rc == 0 and check_result.stdout != '' }}"

- set_fact:
    tern: "{{ acl_exists | ternary('update', 'create') }}"
    acl: "{{lookup('file', acl_name +'.hcl') | trim | regex_replace('[\\r\\n]+','\n')}}"
- debug:
    var: check_result
- debug:
    var: acl_exists
- debug:
    var: tern

- name: "Create ACL {{ acl_name }} policy"
  shell:
    cmd: "consul acl policy {{ tern }} -name '{{ acl_name }}' -token={{ consul_bootstrap_token }} -rules -"
    stdin: "{{acl}}"
