- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled

- name: load br_netfilter kernel module
  modprobe:
    name: br_netfilter
    state: present

- name: add br_netfilter to /etc/modules-load.d
  lineinfile:
    path: /etc/modules-load.d/podman-net.conf
    regexp: '^br_netfilter'
    line: br_netfilter
    create: true

- name: set bridge bridge-nf-call-ip6tables settings
  sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_file: /etc/sysctl.conf
    sysctl_set: yes
    reload: yes
    state: present
  with_items:
  - net.bridge.bridge-nf-call-arptables
  - net.bridge.bridge-nf-call-ip6tables
  - net.bridge.bridge-nf-call-iptables
  - net.ipv4.ip_forward

- sysctl:
    name: net.ipv4.ping_group_range
    value: '0 2000000'
    sysctl_file: /etc/sysctl.conf
    sysctl_set: yes
    state: present
    reload: yes

- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_ssh_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_ssh_host is defined
  with_items: "{{ groups.all }}"

- name: add hostname to /etc/hosts
  vars:
    comment: '# added by ansible'
  lineinfile:
    dest: /etc/hosts
    regexp: "127[.]0[.]0[.]1.*"
    line: "127.0.0.1 localhost.localdomain localhost server.dc1.consul {{ ansible_hostname }} {{ comment }}"
    state: present
    owner: root
    group: root
    mode: '0644'
- name: disable overlay redirection
  copy:
    dest: /etc/modprobe.d/disable-overlay-redirect-dir.conf
    content: "options overlay metacopy=off redirect_dir=off"

#- name: Reload module
#  shell: modprobe -r overlay && modprobe overlay
- name: Fix delegate for cgroups
  copy:
    src: "fix-delegate.sh"
    dest: "/root/"
- name: Copy delegate fix service
  copy:
    src: "fix-delegate.service"
    dest: "/etc/systemd/system/"

- name: Unconditionally reboot the machine with all defaults
  reboot: {}