- name: Generate key {{ key_name }} with cmd
  shell: "{{ cmd }}"
  register: key_cmd

- set_fact:
    "{{ k.name }}": "{{ k.val }}"
  no_log: true
  with_items:
    - { name: "{{ key_name }}", val: "{{key_cmd.stdout}}" }
  loop_control:
    loop_var: k

- name: Save to secrets
  lineinfile:
    dest: "{{ playbook_dir }}/.secrets.yml"
    line: "{{key_name}}: \"{{key_cmd.stdout}}\""
    regexp: "^{{key_name}}: {{key_cmd.stdout}}$"
    create: true
    state: present
  delegate_to: localhost
  become: no
  when: write | default(true)